#!/bin/bash

set -e

if [ $(dpkg-query -W -f='${Status}' zsh | grep -c "install ok installed") -eq 0 ];
then
  sudo apt-get -y install zsh
fi

grep -xq ". ~/.aliases" ~/.bashrc || printf "\n. ~/.aliases\n" >> ~/.bashrc
grep -xq ". ~/.functions" ~/.bashrc || printf "\n. ~/.functions\n" >> ~/.bashrc
grep -xq "export COMMAND_NOT_FOUND_INSTALL_PROMPT=1" ~/.bashrc || printf "\nexport COMMAND_NOT_FOUND_INSTALL_PROMPT=1\n" >> ~/.bashrc

if [ -f "$HOME/.mplayer/config" ];
then
  grep -xq "lirc=no" ~/.mplayer/config || printf "\nlirc=no\n" >> ~/.mplayer/config;
fi

sudo add-apt-repository -y ppa:peterlevi/ppa
sudo apt-get update
sudo apt-get -y install variety

sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get -y install sublime-text-installer

wget https://packagecontrol.io/Package%20Control.sublime-package
mv Package\ Control.sublime-package  /home/$USER/.config/sublime-text-3/Installed\ Packages/Package\ Control.sublime-package

wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

sudo apt-get -y install python-pip
sudo pip install --upgrade pip virtualenv

if [ ! -d "$HOME/.oh-my-zsh" ];
then
  chmod +x tools/install.sh
  sh tools/install.sh
fi
