#!/bin/bash

packages=( "curl" "zsh" )
for i in "${packages[@]}"
do
  if [ $(dpkg-query -W -f='${Status}' $i | grep -c "install ok installed") -eq 0 ];
  then
    sudo -E apt-get -y install $i
  fi
done

grep -xq ". ~/.aliases" ~/.bashrc || printf "\n. ~/.aliases\n" >> ~/.bashrc
grep -xq ". ~/.functions" ~/.bashrc || printf "\n. ~/.functions\n" >> ~/.bashrc
grep -xq "export COMMAND_NOT_FOUND_INSTALL_PROMPT=1" ~/.bashrc || printf "\nexport COMMAND_NOT_FOUND_INSTALL_PROMPT=1\n" >> ~/.bashrc

if [ -f "$HOME/.mplayer/config" ];
then
  grep -xq "lirc=no" ~/.mplayer/config || printf "\nlirc=no\n" >> ~/.mplayer/config;
fi

if [ ! -d "$HOME/.oh-my-zsh" ];
then
  sh -c "$(curl -fsSL https://raw.github.com/swapagarwal/dotfiles/master/tools/install.sh)"
  chsh -s /bin/zsh
fi
